apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: helm-values
data: 
  values.yaml: |
    containers:
    - image: "dscr.io/username/mysql"
      volumeMounts:
      - containerPath: /var/lib/mysql
        volume:
          name: mysql-data
          subPath: /mysql
          readOnly: false
